pipeline{
    agent{
        node{
            label 'workstation'
        }
    }
    options{
        ansiColor('xterm')
    }
    stages{

    stage('apply'){
        steps{
            sh'''
            cd jenkins-ip-update
            terraform init
            terraform apply -auto-approve

            '''

        }
    
      }
    }
     post{
        always {
            cleanWs()
        }
   }
}
